//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastralManagemen_app.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CadastreObjectsTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastreObjectsTB()
        {
            this.RequestTB = new HashSet<RequestTB>();
        }
    
        [Key]
        public int IDcadastreObjects { get; set; }
        public decimal price { get; set; }
        public string typeCadastre { get; set; }
        public System.DateTime registrationDate { get; set; }
        public string comment { get; set; }
        public int IDusers { get; set; }
        public int IDreques { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestTB> RequestTB { get; set; }
    }
}
