//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastralManagemen_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        public int IDengineer { get; set; }
        public string acept { get; set; }
        public string refuse { get; set; }
        public int IDusers { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
